### ISSUE TITLE
Excess range preventing combat from initiating

### ISSUE THREAD

**Issue by Dbeckmacneil** [CaptainX3/NSC2-Issues-Board#35]
I'm not sure if this is 100% due to NSC but I've been having a serious and consistent issue where fleets that contain ships with too much range are unable to enter combat mode, they will not attack or be attacked by other fleets. For example if my titans have the aura's equipped then none of my ships will enter combat. Attached are screenshots of my Flagship and it being ordered to attack a Marauder but not entering combat. The same does not occur with a fleet that consists of Dreadnoughts, Carriers, Strike Cruisers and Destroyers.  
![20190501160608_1](https://user-images.githubusercontent.com/13509933/57039624-2ca64b00-6c2b-11e9-81cd-be1fd71cb8ef.jpg)
![20190501160624_1](https://user-images.githubusercontent.com/13509933/57039625-2d3ee180-6c2b-11e9-9a74-1ffd61517a59.jpg)

**Comment by Dbeckmacneil** [comment]
This is definitely a general issue, for instance here is a solar stronghold that will not engage my fleet (likely because of the X weapons and building's that increase their range.
![20190501205126_1](https://user-images.githubusercontent.com/13509933/57052100-25933300-6c53-11e9-90be-d239f7d8e6bc.jpg)
![Uploading 20190501205130_1.jpg…]()

**Comment by CaptainX3** [comment]
We're aware of this, it is a vanilla bug in the engine itself, known as the "overflow" bug. In addition to weapon ranges, it can also affect any other number in the game, such as shields, hull, armor, military power, etc. In a vanilla game you likely won't come across the bug since vanilla components don't add that many bonuses, but in a modded game, it's very easy to encounter the bug.

There's nothing any modder can do about it. It'll be up to Paradox to fix the bug in the engine itself. Only solution is to remove all range bonuses from weapons that have a base range of more than 200.
